### ISSUE TITLE
which version?

### ISSUE THREAD

**Issue by mmdxl-dcy** [remigenet/TKAN#18]
I'm a newbie, can you just tell me a version of tensorflow, keras, python that can run the code properly?

**Comment by remigenet** [comment]
Hi, that's why the pyproject.toml is made for usually ! Still as I made it backend agnostic it do not install by default a backend as it is in the development dependencies (to avoid downloading tensorflow when installing the package if you are using jax for example)
An easy way to go for you is just using latest versions of all the packages (keras, tensorflow, and tkan) with python 3.11 or 3.12 (it works too in 3.9 or 3.10)
If you have older version of keras/tensorflow or else you can just do pip install keras tensorflow tkan -U (-U means upgrade)
You also have an example in the example section with package installation inside a notebook, if you do not have cuda installed and no nvidia gpu you should just change "jax[cuda12]" by jax (jax alone is CPU version of it, while the other is for gpu enabled version), as you will see in the notebook you need to specify to keras that the backend is jax doing:
import os
BACKEND = 'jax' # You can use any backend here 
os.environ['KERAS_BACKEND'] = BACKEND

which should be done before importing keras
If this is not specified it will use tensorflow which is default for keras

**Comment by mmdxl-dcy** [comment]
Thanks for the reply, it helped me a lot.
